// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutoclickController from "./autoclick_controller"
application.register("autoclick", AutoclickController)

import AutosaveController from "./autosave_controller"
application.register("autosave", AutosaveController)

import AutosubmitController from "./autosubmit_controller"
application.register("autosubmit", AutosubmitController)

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import CollapsableController from "./collapsable_controller"
application.register("collapsable", CollapsableController)

import CollapsibleController from "./collapsible_controller"
application.register("collapsible", CollapsibleController)

import ComboboxController from "./combobox_controller"
application.register("combobox", ComboboxController)

import DarkController from "./dark_controller"
application.register("dark", DarkController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import FormController from "./form_controller"
application.register("form", FormController)

import HideController from "./hide_controller"
application.register("hide", HideController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import PopoverController from "./popover_controller"
application.register("popover", PopoverController)

import PopperController from "./popper_controller"
application.register("popper", PopperController)

import ReadMoreController from "./read_more_controller"
application.register("read-more", ReadMoreController)

import ReplyController from "./reply_controller"
application.register("reply", ReplyController)

import RevealController from "./reveal_controller"
application.register("reveal", RevealController)

import ShareController from "./share_controller"
application.register("share", ShareController)

import SupportedController from "./supported_controller"
application.register("supported", SupportedController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)

import ThumbnailController from "./thumbnail_controller"
application.register("thumbnail", ThumbnailController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)

import ViewportClickController from "./viewport_click_controller"
application.register("viewport-click", ViewportClickController)

import YoutubeController from "./youtube_controller"
application.register("youtube", YoutubeController)
