// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutoclickController from "./autoclick_controller.js"
application.register("autoclick", AutoclickController)

import ClipboardController from "./clipboard_controller.js"
application.register("clipboard", ClipboardController)

import ComboboxController from "./combobox_controller.js"
application.register("combobox", ComboboxController)

import DarkModeController from "./dark_mode_controller.ts"
application.register("dark-mode", DarkModeController)

import DrawerController from "./drawer_controller.ts"
application.register("drawer", DrawerController)

import DropdownController from "./dropdown_controller.js"
application.register("dropdown", DropdownController)

import DropzoneController from "./dropzone_controller.js"
application.register("dropzone", DropzoneController)

import FilterController from "./filter_controller.js"
application.register("filter", FilterController)

import FlashController from "./flash_controller.js"
application.register("flash", FlashController)

import FormController from "./form_controller.js"
application.register("form", FormController)

import PopperController from "./popper_controller.js"
application.register("popper", PopperController)

import ReplyController from "./reply_controller.js"
application.register("reply", ReplyController)

import SlimselectController from "./slimselect_controller.js"
application.register("slimselect", SlimselectController)

import SlimselectEditController from "./slimselect_edit_controller.js"
application.register("slimselect-edit", SlimselectEditController)

import ThumbnailController from "./thumbnail_controller.js"
application.register("thumbnail", ThumbnailController)

import ToggleController from "./toggle_controller.js"
application.register("toggle", ToggleController)

import TomSelectController from "./tom_select_controller.js"
application.register("tom-select", TomSelectController)

import TomSelectEditController from "./tom_select_edit_controller.js"
application.register("tom-select-edit", TomSelectEditController)

import YoutubeController from "./youtube_controller.js"
application.register("youtube", YoutubeController)
