// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutocompleteController from "./autocomplete_controller.js"
application.register("autocomplete", AutocompleteController)

import ClipboardController from "./clipboard_controller.js"
application.register("clipboard", ClipboardController)

import FilterController from "./filter_controller.js"
application.register("filter", FilterController)

import FlashController from "./flash_controller.js"
application.register("flash", FlashController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import PopperController from "./popper_controller.js"
application.register("popper", PopperController)

import SlimselectController from "./slimselect_controller.js"
application.register("slimselect", SlimselectController)

import SlimselectEditController from "./slimselect_edit_controller.js"
application.register("slimselect-edit", SlimselectEditController)

import ToggleController from "./toggle_controller.js"
application.register("toggle", ToggleController)

import YoutubeController from "./youtube_controller.js"
application.register("youtube", YoutubeController)
