development:
  adapter: redis
  channel_prefix: tangotube_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch('REDIS_URL') { "redis://localhost:6379/1" } %>
  channel_prefix: tangotube_production
  ssl_params:
    verify_mode: <%= OpenSSL::SSL::VERIFY_NONE %>
