service: tangotube
image: jmarsh24/tangotube
servers:
  web:
    hosts:
      - 202.61.197.241
    options:
      add-host: host.docker.internal:host-gateway

registry:
  username:
    - DOCKER_HUB_USERNAME
  password:
    - DOCKER_HUB_TOKEN

env:
  secret:
    - RAILS_MASTER_KEY

accessories:
  db:
    image: postgres:latest
    host: 202.61.197.241
    port: 172.17.0.1:5432:5432
    env:
      secret:
        - POSTGRES_USER
        - POSTGRES_PASSWORD
        - POSTGRES_DB
    directories:
      - data:/var/lib/postgresql/data
  redis:
    image: redis:7.0.3
    hosts:
      - 202.61.197.241
    port: 172.17.0.1:6379:6379
    directories:
      - data:/data
