service: tangotube
image: jmarsh24/tangotube
servers:
  - 167.172.106.219
  - 64.225.107.163

registry:
  server: registry.digitalocean.com
  username:
    - MRSK_REGISTRY_TOKEN
  password:
    - MRSK_REGISTRY_TOKEN

env:
  secret:
    - RAILS_MASTER_KEY
