service: tangotube

image: jmarsh24/tangotube

servers:
  web:
    hosts:
      - 168.119.239.114
    cmd: bundle exec puma -C config/puma.rb
  worker:
    hosts:
      - 159.69.149.32
    cmd: bundle exec good_job start
registry:
  server: ghcr.io
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD
env:
  clear:
    DB_HOST: 128.140.105.113
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
    - HEROKU_DATABASE_URL
    - ENABLE_MAILERS
    - RAILS_MAX_THREADS
    - NEW_RELIC_AGENT_ENABLED
    - NEW_RELIC_APP_NAME
    - NEW_RELIC_LOG
    - BASE_URI
    - AWS_REGION
    - AWS_BUCKET
    - YT_DLP_BIN
    - CLOUDFLARE_BUCKET

builder:
  args:
    RUBY_VERSION: 3.2.2
    RAILS_ENV: production
    NODE_VERSION: 18.12.0
    YARN_VERSION: 1.22.19
  multiarch: false

accessories:
  db:
    image: postgres:15
    host: 128.140.105.113
    port: 5432
    env:
      clear:
        POSTGRES_USER: "postgres"
        POSTGRES_DB: "tangotube_production"
      secret:
        - POSTGRES_PASSWORD
    files:
      - config/postgres/production.cnf:/etc/postgresql/postgres.conf
    volumes:
      - /var/postgres/data:/var/lib/postgresql/data

healthcheck:
  log_lines: 10_000
