service: tangotube
image: jmarsh24/tangotube
servers:
  - 167.172.106.219
  - 64.225.107.163

registry:
  username: jmarsh24

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    MEMCACHED_HOST: 192.168.0.3

accessories:
  memcached:
    image: memcached:latest
    host: 192.168.0.3
    port: 11211
