service: tangotube

image: jmarsh24/tangotube

servers:
  web:
    hosts:
      - 168.119.239.114
    cmd: bundle exec puma -C config/puma.rb
  worker:
    hosts:
      - 49.13.145.88
    cmd: bundle exec good_job start
registry:
  server: ghcr.io
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD
env:
  clear:
    DB_HOST: 128.140.105.113
    HOST: tangotube.tv
    YT_DLP_BIN: /opt/venv/bin/yt-dlp
    KAMAL_CONTAINER_NAME: tangotube
    STATEMENT_TIMEOUT: 15000
    LOCK_TIMEOUT: 5000
    RAILS_MAX_THREADS: 5
    DB_POOL: 40
    WEB_CONCURRENCY: 4
    GOOD_JOB_MAX_THREADS: 4
    NEW_RELIC_APP_NAME: tangotube
    NEW_RELIC_REGION: EU
    NEW_RELIC_ACCOUNT_ID: 3766249
    NEW_RELIC_AGENT_ENABLED: true
    NEW_RELIC_LOG: stdout
    ENABLE_MAILERS: 1
    BASE_URI: tangotube.tv
    CLOUDFLARE_BUCKET: tangotube
    AWS_REGION: eu-central-1
    AWS_BUCKET: tangotube
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
    - ACR_CLOUD_ACCESS_KEY
    - ACR_CLOUD_SECRET_KEY

builder:
  multiarch: false

accessories:
  db:
    image: postgres:15
    host: 128.140.105.113
    port: 5432
    env:
      clear:
        POSTGRES_USER: "postgres"
        POSTGRES_DB: "tangotube_production"
      secret:
        - POSTGRES_PASSWORD
    volumes:
      - /var/postgres/data:/var/lib/postgresql/data

healthcheck:
  log_lines: 10_000
