service: tangotube

image: jmarsh24/tangotube

servers:
  web:
    hosts:
      - 202.61.197.241
    # labels:
    #   traefik.http.routers.tangotube-web.rule: Host(`domain.com`)
    #   traefik.http.services.tangotube-web.loadbalancer.healthcheck.interval: 45s
  job:
    hosts:
      - 202.61.197.241
    cmd: bundle exec sidekiq -C config/sidekiq.yml

registry:
  username:
    - DOCKER_HUB_USERNAME
  password:
    - DOCKER_HUB_TOKEN

env:
  clear:
    RAILS_SERVE_STATIC_FILES: true
    RAILS_ENV: production
    YT_DLP_BIN: yt-dlp
  secret:
    - RAILS_MASTER_KEY
    - REDIS_URL
    - DATABASE_URL

volumes:
  - "/opt/app_system:/rails/public/system"
  - "/backup:/backup"

builder:
  dockerfile: Dockerfile
  multiarch: false
  remote:
    arch: amd64
    host: ssh://root@202.61.197.241

accessories:
  db:
    image: postgres:15
    host: 202.61.197.241
    port: "5432:5432"
    env:
      secret:
        - POSTGRES_USER
        - POSTGRES_PASSWORD
        - POSTGRES_DB
    files:
      - db/production.sql:/docker-entrypoint-initdb.d/setup.sql
    directories:
      - dataPg:/var/lib/postgresql/data
  redis:
    image: redis:7.0
    cmd: redis-server --requirepass <%= ENV['REDIS_PASSWORD'] %>
    host: 202.61.197.241
    port: "6379:6379"
    directories:
      - dataRedis:/data

healthcheck:
  path: /up
  port: 3000
