service: tangotube

image: jmarsh24/tangotube

servers:
  web:
    hosts:
      - 202.61.197.241
  job:
    hosts:
      - 202.61.197.241
    cmd: bundle exec sidekiq -C config/sidekiq.yml
registry:
  username:
    - DOCKER_HUB_USERNAME
  password:
    - DOCKER_HUB_TOKEN

env:
  clear:
    RAILS_SERVE_STATIC_FILES: true
    RAILS_ENV: production
    YT_DLP_BIN: yt-dlp
    REDIS_URL: redis://202.61.197.241:6379
    REDIS_CACHE_URL: redis://202.61.197.241:6380
  secret:
    - RAILS_MASTER_KEY
    - DATABASE_URL

volumes:
  - "/opt/app_system:/rails/public/system"
  - "/backup:/backup"
  - ./log:/app/log

builder:
  dockerfile: Dockerfile
  remote:
    arch: amd64
    host: ssh://root@202.61.197.241

accessories:
  db:
    image: postgres:latest
    host: 202.61.197.241
    port: 5432
    env:
      secret:
        - POSTGRES_USER
        - POSTGRES_PASSWORD
        - POSTGRES_DB
    files:
      - db/production.sql:/docker-entrypoint-initdb.d/setup.sql
    directories:
      - dataPg:/var/lib/postgresql/data
  redis_sidekiq:
    image: redis:latest
    host: 202.61.197.241
    port: 6379
    directories:
      - sidekiqData:/data
  redis_cache:
    image: redis:latest
    host: 202.61.197.241
    port: 6380
    directories:
      - cacheData:/data

healthcheck:
  path: /up
  port: 3000
