name: CI

on: [push]

env:
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

jobs:
  ruby:
    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: app
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
      - name: Install OS packages
        run: |
          sudo add-apt-repository universe
          sudo apt-get update
          sudo apt-get install -y ffmpeg
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: yarn
      - name: Install yarn
        run: yarn install
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Lint
        run: bundle exec rubocop -c .rubocop.yml
      # - name: Translations Lint
      #   run: bundle exec i18n-tasks health
      - name: Check Controllers Route Annotations
        run: bundle exec chusaku --exit-with-error-on-annotation
        env:
          # some of the routes are only defined in test
          RAILS_ENV: test
      - name: Check Model Annotations
        run: bundle exec annotate --models && bin/git_tracked_are_unmodified
        env:
          DATABASE_URL: postgres://postgres:postgres@127.0.0.1:5432/app
          RAILS_ENV: test
      # - name: JS Lint
      #   run: yarn lint
      - name: Create PG Database
        run: bundle exec rake db:create db:migrate
        env:
          DATABASE_URL: postgres://postgres:postgres@127.0.0.1:5432/app
          RAILS_ENV: test
      - name: Build and test with Rake
        run: bundle exec rspec --format documentation
        env:
          DATABASE_URL: postgres://postgres:postgres@127.0.0.1:5432/app
          REDIS_URL: redis://127.0.0.1:6379
          RAILS_ENV: test
          RSPEC_RETRY_RETRY_COUNT: 3
