name: Production Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    env:
      DOCKER_BUILDKIT: 1
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}
      KAMAL_REGISTRY_USERNAME: ${{ vars.KAMAL_REGISTRY_USERNAME }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Install necessary dependencies and build tools
      - name: Install build dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install --no-install-recommends -y build-essential curl git libvips libpq-dev pkg-config nodejs

      # Install specific Node and Yarn versions
      - name: Install Node and Yarn
        env:
          NODE_VERSION: 18.17.1
          YARN_VERSION: 1.22.19
        run: |
          sudo curl -sL https://github.com/nodenv/node-build/archive/master.tar.gz | sudo tar xz -C /tmp/
          sudo /tmp/node-build-master/bin/node-build "${NODE_VERSION}" /usr/local/node
          sudo npm install -g yarn@$YARN_VERSION

      # Install Ruby from source
      - name: Install Ruby
        run: |
          wget https://cache.ruby-lang.org/pub/ruby/3.2/ruby-3.2.2.tar.gz
          tar xzf ruby-3.2.2.tar.gz
          cd ruby-3.2.2
          ./configure
          make
          sudo make install

      # Check Ruby and Bundler version
      - name: Check Ruby and Bundler version
        run: |
          ruby --version
          gem install bundler
          bundle --version

      # Bundle install
      - name: Install gems
        run: |
          bundle install
          bundle exec bootsnap precompile --gemfile

      # Install npm packages
      - name: Install npm packages
        run: |
          yarn install

      # Compile application assets
      - name: Compile assets
        run: |
          bundle exec bootsnap precompile app/ lib/
          SECRET_KEY_BASE_DUMMY=1 ./bin/rails assets:precompile

      - name: Install kamal
        run: gem install kamal

      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/arm64

      - uses: docker/build-push-action@v5
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Copy Config
        run: cp config/deploy.yml.prod config/deploy.yml

      - name: Deploy Application
        run: kamal deploy
