name: Production Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    env:
      DOCKER_BUILDKIT: 1
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}
      KAMAL_REGISTRY_USERNAME: ${{ vars.KAMAL_REGISTRY_USERNAME }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ruby dependencies
        run: |
          sudo apt update
          sudo apt install -y libssl-dev libreadline-dev zlib1g-dev

      - name: Install Ruby from source
        run: |
          wget https://cache.ruby-lang.org/pub/ruby/3.2/ruby-3.2.2.tar.gz
          tar xzf ruby-3.2.2.tar.gz
          cd ruby-3.2.2
          ./configure
          make
          sudo make install

      - name: Check Ruby and Bundler version
        run: |
          ruby --version
          gem install bundler
          bundle --version

      - name: Install kamal
        run: gem install kamal

      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/arm64

      - uses: docker/build-push-action@v5
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Copy Config
        run: cp config/deploy.yml.prod config/deploy.yml

      - name: Deploy Application
        run: kamal deploy
