name: Production Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: buildjet-4vcpu-ubuntu-2204-arm

    env:
      DOCKER_BUILDKIT: 1
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}
      KAMAL_REGISTRY_USERNAME: ${{ vars.KAMAL_REGISTRY_USERNAME }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install rbenv and ruby-build
        run: |
          sudo apt-get update
          sudo apt-get install -y rbenv ruby-build
          echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
          source ~/.bashrc
          rbenv init

      - name: Install Ruby
        run: |
          rbenv install 3.2.2
          rbenv global 3.2.2
          ruby -v

      - name: Install kamal
        run: command -v kamal &> /dev/null || gem install kamal

      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Copy Config
        run: cp config/deploy.yml.prod config/deploy.yml

      - name: Deploy Application
        run: kamal deploy
