name: Production Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: buildjet-4vcpu-ubuntu-2204-arm

    env:
      DOCKER_BUILDKIT: 1
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}
      KAMAL_REGISTRY_USERNAME: ${{ vars.KAMAL_REGISTRY_USERNAME }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ruby-build
        run: |
          git clone https://github.com/rbenv/ruby-build.git
          PREFIX=/usr/local sudo ./ruby-build/install.sh

      - name: Install Ruby
        run: |
          ruby-build 3.2.2 /opt/hostedtoolcache/Ruby/3.2.2/arm64
          touch /opt/hostedtoolcache/Ruby/3.2.2/arm64.complete

      - name: Set up Ruby Environment
        run: |
          echo "/opt/hostedtoolcache/Ruby/3.2.2/arm64/bin" >> $GITHUB_PATH
          echo "GEM_HOME=$RUNNER_HOME/.gem/ruby/3.2.2" >> $GITHUB_ENV
          echo "GEM_PATH=$GEM_HOME" >> $GITHUB_ENV

      - name: Install kamal
        run: command -v kamal &> /dev/null || gem install kamal

      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Copy Config
        run: cp config/deploy.yml.prod config/deploy.yml

      - name: Deploy Application
        run: kamal deploy
