name: Publish Docker image to GHCR

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: tangotube
  REGISTRY: ghcr.io

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build . --tag $IMAGE_NAME

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login $REGISTRY -u ${{ github.actor }} --password-stdin

      - name: Push Docker Image to GHCR
        run: |
          IMAGE_ID=$REGISTRY/${{ github.repository_owner }}/${IMAGE_NAME,,}
          docker tag $IMAGE_NAME $IMAGE_ID:latest
          docker push $IMAGE_ID:latest
